### ISSUE TITLE
Start using pull request/merge model

### ISSUE THREAD

**Issue by ericvaandering** [dmwm/CMSKubernetes#1]
Now that you have a fork, it'd be good to start using a more formal development model for the repo. :-)

**Comment by vkuznet** [comment]
How about:
- move das2go, dbs2go, dbs3 into docker directory to make it more clear
- and I can reorganize docs a little bit into sections under doc directory, e.g. docker.md, kubernetes.md, etc.
- I'm fine to move entire repository under dmwm too at any time.

**Comment by ericvaandering** [comment]
That all sounds good and I have no opinion about the directory structure. Unrelated to my suggestion, though.

**Comment by vkuznet** [comment]
In this case I don't think I need to do anything right away. Once you'll create
your PR we can proceed with review/merge process.

I'll refactor docs/dirs sometime next week.
