### ISSUE TITLE
[Introduction.md]The proxy.sh mentioned is missing.

### ISSUE THREAD

**Issue by cronosnull** [dmwm/CMSKubernetes#120]
In the `introduction.md`  tutorial there is a mention to a proxy.sh from the frontend folder, linked to ` `docker/frontend/proxy.sh`, which is missing. 
I guess it should be [docker/proxy/proxy.sh](https://github.com/dmwm/CMSKubernetes/blob/master/docker/proxy/proxy.sh)

**Comment by vkuznet** [comment]
Fixed in 4e915f7..c0a897e commit
