### ISSUE TITLE
Incorporating new robot certificates for crab and dmwm namespaces.

### ISSUE THREAD

**Issue by arooshap** [dmwm/CMSKubernetes#1353]
Hi,

Following the discussion we had at [CMSKUBERNETES-229](https://its.cern.ch/jira/browse/CMSKUBERNETES-229), I created separate robot accounts for CRAB and DMWM. After obtaining the certificates, I made sure that they have they are configured properly and have the same permissions as they had previously. 

Since we deploy these certificates as `cluster-secrets` through the [deploy-cluster-secrets.sh](https://github.com/dmwm/CMSKubernetes/blob/master/kubernetes/cmsweb/scripts/deploy-cluster-secrets.sh) script, I made some changes in this script to have proper certificate according to the namespace, which can be reviewed here: https://github.com/dmwm/CMSKubernetes/pull/1351. If you have any suggestions to make it more efficient, let me know.

We can deploy these secrets in the dev clusters, and once we are sure that the services are working properly, we can then deploy the changes in testbed, and eventually production. Let me know your suggestions in this regard as well.

**Note that this change does not require any of the teams to modify their deployment or kubernetes manifest files**

**Comment by arooshap** [comment]
FYI @amaltaro, @todor-ivanov, @vkuznet, @mapellidario.

**Comment by mapellidario** [comment]
Aroosha updated the robot certificates in the crab namespace in the testbed cluster [1].
I submitted a test task to testbed and everything looks ok to me [2]. 

I give green light to change the robot certificate for CRAB on the prod cluster.

[1] the certificate at path now is owned by the DN: `Subject: DC=ch, DC=cern, OU=Organic Units, OU=Users, CN=crabcms, CN=852819, CN=Robot: CRAB CMS Web Service Account`

[2] https://cmsweb-testbed.cern.ch/crabserver/ui/task/230417_140021%3Admapelli_crab_robot_20230417_160000

**Comment by arooshap** [comment]
Hi @amaltaro @todor-ivanov, do you have any updates for us on this ticket?
