### ISSUE TITLE
how to change CRABServer installation variant

### ISSUE THREAD

**Issue by belforte** [dmwm/CMSKubernetes#168]
@vkuznet @muhammadimranfarooqi  with reference to
https://github.com/dmwm/CMSKubernetes/blob/52bbeeef606723f6ed01aed0aaed381369f5cff3/docker/crabserver/install.sh#L7

currently the procedure in this repository builds a crabserver preprod flavor.
The 'preprod' tag there refernce to once specific Oracle DataBase instance.
There are 3 such instance: prod, preprod and dev which allows us to
test and validate things and we will eventually need to have all in K8s.

What is the suggested way to manage this ?
so far @ddaina has switched cmsweb-test2 from preprod to test by building
the container with a modified file, but this is a fragile procedure in the long term.
I see that we have some cluster-specific files in
https://gitlab.cern.ch/cmsweb-k8s
while in this github.com/dmwm/CMSKubernetes repository files are generic for all clusters
But I do not see a place where e.g. customize the k8s yaml files.

One possibility that comes to mind is to allow building different containers: crabserver-prod, crabserver-preprod, crabserver-dev with different versions of https://github.com/dmwm/CMSKubernetes/blob/52bbeeef606723f6ed01aed0aaed381369f5cff3/docker/crabserver/install.sh#L7 and use the appropriate one as image in the various yaml files.
What do you think ?

**Comment by vkuznet** [comment]
Stefano,
the best way to deal with different configurations is to supply it externally. Is it possible for the CRAB server? The external configuration may specify which server to use, e.g. prod, prepared, etc. If this is possible it will solve the problem. Otherwise, we will need to build different images and use different deployment manifest files. Since neither I or Muhammad are familiar with CRAB internals it is up to you to tell us how certain instances can be configured and deployed.

The gitlab repository is a perfect example where we can store individual configurations and then adjust k8s manifest files to supply these configuration files. But this implies that crab service should be able to read them and run accordingly.

**Comment by belforte** [comment]
Thanks Valentin. Currently we need both, and more. I explain below:
Both: an external configuration file for prod/pre/dev and a change in the install script
More: using a different Oracle DB requires not only a different config, but also a different secret file.

I suspect that we can change the code so that whatever different action the install.sh
script does is driven by some configuration file, but this is not code which I wrote and
as you know cms pkgtools is a bit hard to master for someone like me. I will look, but
we may want to start with something simpler even if less elegant.

Anyhow I taket this as indication that @ddaina can create cluster specific files in that gitlab repository
as she walks her way into making all of this fully configuration driven.

About secrets, AFAIU it is a manual procedure and may stay so due to security. Imran has taught Prajesh how to change secrets and Prajesh have changed it for cmsweb-test(1-6) clusters to use credentials for 'dev', instead of 'preprod'.  But I do not know how this could be simplified or made
automatic.

**Comment by belforte** [comment]
by the way @vkuznet can you make cmsweb-test.cern.ch use 'dev' for crabserver as well ? We do not have access to that cluster, but if you decide to test crabserver there it may be better that it stays with the development DB.

**Comment by vkuznet** [comment]
Stefano, I don't have time for it now, but I suggest that you develop an external configuration that we can incorporate to the deployment such that we can specify through it how to deploy and which DB to use.

**Comment by belforte** [comment]
Thanks Valentin. I believe I understand enough about the clusters now to be able to come up with such a solution with @ddaina help.
