### ISSUE TITLE
clean-up helm area (rucio tar balls)

### ISSUE THREAD

**Issue by vkuznet** [dmwm/CMSKubernetes#703]
We need to remove all tar balls from help area. @ericvaandering could you please take care of that.

**Comment by ericvaandering** [comment]
Why? This is how helm publishes things. But I can try to figure out how Rucio does this by putting those things into a separate branch from master/main.

**Comment by vkuznet** [comment]
I don't know how helm handle things, but for cmsweb folder (under helm) we don't have tar balls. Moreover, you have multiple versions of tarballs which I think some of them are obsolete. I suggest that if you do require store tarballs put them under rucio folder(s) to clean up the area. I also see that there is (a possible) redundancy in directory structure, since you do have untarred areas along with tarballs, e.g.
```
rucio-consistency
rucio-consistency-0.1.0.tgz
rucio-cron-jobs
rucio-cron-jobs-0.1.0.tgz
rucio-cron-jobs-0.2.0.tgz
rucio-loadtest
rucio-statsd-exporter
rucio-statsd-exporter-0.1.0.tgz
rucio-statsd-exporter-1.0.0.tgz
rucio-statsd-exporter-1.0.1.tgz
rucio-traces
rucio-traces-0.1.0.tgz
```
and if I list one particular rucio area I see that it context represents a tar ball one.

**Comment by ericvaandering** [comment]
Right, that's all as it should be for helm to use the GH repository as a helm repo. It uses the tarballs in that case and, of course, each is a release.

**Comment by vkuznet** [comment]
that's fine then, but I still confused why help need both a tar ball and the actual area. I think one is enough to make another. And, versions can be part of git tag. Anyway, I trust you in this, but as we move to helm too (Muhammad's student is working and pushing stuff to heml/cmsweb area) I don't see tar balls over there. If you think that everything is fine I can close the ticket.

**Comment by vkuznet** [comment]
ok, then I'll close the ticket.
