### ISSUE TITLE
Documentation for a cmsweb-like dev environment

### ISSUE THREAD

**Issue by amaltaro** [dmwm/CMSKubernetes#73]
Valentin, as we discussed in the past week, it would be extremely useful to many CMSWEB applications developers on how one can run a full deployment as we have nowadays.
Which means, deploying the service we want to deploy together with the frontend, frontend rules, frontend accounts/certificates mapping and so on, such that we can have the complete cycle and test services as they would get deployed in a production environment.

Something along the lines as https://github.com/dmwm/CMSKubernetes/blob/master/kubernetes/cmsweb-nginx/docs/end-to-end.md , but really end-to-end ;)

**Comment by vkuznet** [comment]
Alan, did you read this documentation
https://github.com/dmwm/CMSKubernetes/blob/master/kubernetes/cmsweb-nginx/docs/cmsweb-deployment.md

It contains everything you/others need to know for end-to-end for cmsweb of the cluster, including cluster creation, deployment of frontend and services clusters, LanDB registration, labeling the nodes, and cluster maintenance. Please read and try it (once we get the quotas) and then we can discuss here what is missing.

**Comment by vkuznet** [comment]
The [cmsweb-deployment documentation](https://github.com/dmwm/CMSKubernetes/blob/master/kubernetes/cmsweb-nginx/docs/cmsweb-deployment.md) provides all instructions from end-to-end therefore I'm closing the ticket. If something is missing documentation or unclear please open up a new ticket on particular issue.
