### ISSUE TITLE
Cannot have two different directories of helm charts

### ISSUE THREAD

**Issue by ericvaandering** [dmwm/CMSKubernetes#783]
The chart releaser action overwrites things when it's like that. The Rucio ones are overwritten if you update a cmsweb or vice versa. 

So there are only two possibilities. We all put our charts in the same directory (and if that's what we want, I'll make the PR since it's a little bit tricky) or we just move the Rucio stuff to it's own repository. Maybe CMSKubernetes has outgrown it's usefulness. Up to you. @arooshap @muhammadimranfarooqi @vkuznet

**Comment by ericvaandering** [comment]
Hi all. This is now working, although you may have to update the chart version #'s to a new chart built for each of them. I've done everything alphabetically through "DBS"

This is being published on GitHub.io via the "Pages" setting for the Repo, so please don't change anything there. @arooshap , @vkuznet told me you had an alternate idea of publishing to CERN's registry. If you get that working, please let me know where to find the charts in that case

**Comment by vkuznet** [comment]
@arooshap , please perform the following actions:
- remove charts from public hub repo you showed in a meeting (sorry I already forgot its name)
- add proper workflow step to publish charts to CERN registry, if necessary please get details from Spyros
- update slides and tutorial to use CERN registry
- add documentation to use CERN registry for helm charts publication
