### ISSUE TITLE
Add docker login instructions on the building documentation

### ISSUE THREAD

**Issue by amaltaro** [dmwm/CMSKubernetes#81]
As just discussed on the training, please add instructions highlighting how one can upload the images to docker hub to:
https://github.com/dmwm/CMSKubernetes/blob/master/docker/README.md#how-to-build-docker-image-for-cms-data-service

**Comment by vkuznet** [comment]
The instructions clearly says:
```
Then you can upload your image to the docker hub:

docker push USERNAME/das:tagname
```

Do you need anything more than that?

**Comment by amaltaro** [comment]
I guess that's what this issue was about. Thanks
