### ISSUE TITLE
add redirection ruls for CRAB schedds to FrontEnd

### ISSUE THREAD

**Issue by belforte** [dmwm/CMSKubernetes#87]
as done in current frontend:
https://github.com/dmwm/deployment/blob/27580b5863583abcd7557003008d3c1a66737b48/frontend/backends-prod.txt#L15-L34

as discussed in
https://hypernews.cern.ch/HyperNews/CMS/get/webInterfaces/1699/1.html

I know that such an explicit list of VM names is not nice, but it it can be accomodated, it surely is much less work then alternatives. All in all that list changes very rarely.

**Comment by belforte** [comment]
@muhammadimranfarooqi I think this was done, since links like
https://cmsweb-testbed.cern.ch/scheddmon/0106/cms1627/
currently work. Can you confirm ?
We also need to know how this will be managed in the future. Next time Prajesh adds one CRAB schedd or change name to one, what do we need to do in order to have the redirection rule ?
thanks

**Comment by muhammadimranfarooqi** [comment]
@belforte 

I have incorporated new redirection rules for the k8s testbed cluster. (https://cmsweb-k8s-testbed.cern.ch/scheddmon/0106/cms1627/) . 

You can find them here. 

https://github.com/dmwm/deployment/blob/master/frontend/backends-k8s.txt

Every time, when there is a need to change, the changes should be done in both VM testbed and k8s cluster redirection rules. 

best
M Imran

**Comment by belforte** [comment]
thanks @muhammadimranfarooqi 
I have updated the instruction for installing new CRAB schedd's with this information :+1: https://twiki.cern.ch/twiki/bin/view/CMSPublic/ScheddDeployment#Redirection_rules_for_CMSWEB
