### ISSUE TITLE
Helmchart publication is not working

### ISSUE THREAD

**Issue by ericvaandering** [dmwm/CMSKubernetes#888]
From the latest action:

myrepo	https://registry.cern.ch/chartrepo/cmsweb
19
Successfully packaged chart and saved it to: /home/runner/work/CMSKubernetes/CMSKubernetes/helm/rucio-consistency-0.4.2.tgz
20
Error: unknown flag: --username

And I confirm that none of the Rucio charts have been updated on the CERN repo in months. Can one of you fix this ASAP? We need this to be able to fully clean up the CERN site.

**Comment by muhammadimranfarooqi** [comment]
Hi @ericvaandering 

`helm push` has been replaced by `helm cm-push`. I have corrected this. Now should be fine. Thanks for reporting
